[package]
name = "statemap"
version = "0.1.0"
authors = ["Bryan Cantrill <bryan@joyent.com>"]

[dependencies]
memmap = "0.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
natord = "1.0.9"
palette = "0.4"
rand = "0.5"
structopt = "0.2"
